import assert from 'node:assert/strict';
import {inSlice,DECAY_BINS,treeBoost,decayKind,gu,gv,DECAY,applyDecay} from '../dist/campus/atmosphere/decay.js';
import {flicker} from '../dist/campus/atmosphere/night.js';
import {crowdPlan} from '../dist/campus/atmosphere/crowd.js';
import {SPEAKER} from '../dist/soundtrack.js';
import data from '../dist/campus/data/campus-data.js';
import {pointInRing,centroid} from '../dist/campus/geometry.js';
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('ok - '+name);};
const B=bin=>data.buildings.find(b=>b.bin===bin);
test('decay slice covers the park and the facing landmarks but never the Brown Building',()=>{
 for(const bin of Object.values(DECAY_BINS))assert.ok(inSlice(centroid(B(bin).rings[0])),'in slice '+bin);
 assert.ok(!Object.values(DECAY_BINS).includes(1008823));assert.ok(!inSlice(centroid(B(1008823).rings[0])),'Brown outside the slice');
 assert.ok(inSlice([-30,-46]),'fountain');});
test('park trees grow most over the century; street trees grow less',()=>{const park=data.areas.find(a=>a.kind==='park'&&pointInRing([-30,-46],a.ring)).ring;
 const inside=data.trees.find(t=>pointInRing(t.p,park)),outside=data.trees.find(t=>!pointInRing(t.p,park)&&!inSlice(t.p));
 assert.ok(treeBoost(inside.p,park).height>1.5);const o=treeBoost(outside.p,park);assert.ok(o.height>1.2&&o.height<treeBoost(inside.p,park).height+.31&&o.crown<2.2);});
test('weathering kinds by material name',()=>{assert.equal(decayKind('glassClear'),'glass');assert.equal(decayKind('iron'),'metal');assert.equal(decayKind('sign'),'light');assert.equal(decayKind('brick'),'masonry');});
test('lamp flicker stays between 0 and 1 and some lamps go dark',()=>{let dark=0;for(let i=0;i<400;i++){const v=flicker(i*.13,.9);assert.ok(v>=0&&v<=1);if(v===0)dark++;}assert.ok(dark>0);for(let i=0;i<50;i++)assert.ok(flicker(i,.2)>.6);});
import {buildTier2Geometry} from '../dist/campus/tier2/world.js';
const t2doors=buildTier2Geometry(data.buildings,(x,n)=>Math.floor(x/120)+','+Math.floor(n/120)).doors;
test('crowds: the park slice roles plus queues at NYU doors and people on the plazas, never inside a building or near the Brown Building',()=>{const {people,doors}=crowdPlan(data,{doors:t2doors});
 assert.ok(people.length>600&&people.length<2500,'count '+people.length);assert.equal(doors.length,2);const roles=new Set(people.map(p=>p.role));
 for(const r of ['queue','reader','wall','lecture','lecturer','class','loiter','tree','steps','chess'])assert.ok(roles.has(r),'role '+r);
 assert.ok(people.some(p=>p.pose==='gown')&&people.some(p=>p.pose==='seat'));assert.ok(people.filter(p=>!inSlice(p.home)).length>300,'beyond the park slice');
 const brown=centroid(B(1008823).rings[0]);for(const p of people)assert.ok(Math.hypot(p.home[0]-brown[0],p.home[1]-brown[1])>40);
 const near=data.buildings.filter(b=>people.some(p=>Math.abs(b.rings[0][0][0]-p.home[0])<150&&Math.abs(b.rings[0][0][1]-p.home[1])<150));
 for(const p of people)if(p.role!=='wall'&&p.role!=='reader')for(const b of near)assert.ok(!pointInRing(p.home,b.rings[0]),p.role+' inside '+b.bin);});
test('the broken loudspeaker stands just south of the Arch, on open ground',()=>{assert.ok(Math.hypot(SPEAKER.x,SPEAKER.z)<25);assert.ok(Math.hypot(SPEAKER.x+30,SPEAKER.z+46)>20,'clear of the fountain');});
test('the decay layer is one shared level that hooks follow, from clean 2026 (0) to the 2126 ruin (1)',()=>{const seen=[];const w={decayHooks:[t=>seen.push(t)]};
 applyDecay(w,0);assert.equal(DECAY.value,0);applyDecay(w,.5);applyDecay(w,1);assert.deepEqual(seen,[0,.5,1]);assert.equal(DECAY.value,1);});
console.log('atmosphere: '+passed+' passed');
